name: cs442_mp6
description: "CS 442 final project"
publish_to: 'none' 
version: 1.0.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  url_launcher: ^6.1.7
  test: ^1.24.0

  provider: ^6.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  http: ^1.1.0
  html: ^0.15.0
  collection: ^1.17.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  # to add assets to the app, do something like this:
  # assets: 
  #   - assets/
