name: cs442_mp4
description: Flashcards
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.5.0'

dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flashcards.json
